### ISSUE TITLE
Feature request: Show total number of CI builds (pending)

### ISSUE THREAD

**Issue by sawenzel** [alisw/ali-bot#436]
Currently I see in AliceO2:

All checks have passed
3 successful checks

although that we are running 4 tests. I think it would be useful to say: Currently 3 out of 4 tests have passed ... 1 build is pending.

**Comment by ktf** [comment]
Again, I think this has improved a lot recently, both thanks to the protected branches and the new features developed by timo. Feel free to bring new requests to WP3.
