### ISSUE TITLE
Feature request: disable merge button when tests fail

### ISSUE THREAD

**Issue by sawenzel** [alisw/ali-bot#437]
As a user I would like to only merge commits for which all tests pass.
To prevent "accidential"  merging, I would be in favour of disabling the merge button as long as the tests are running or when they fail.

To still allow for forced merges, the user could enable the merge button manually by saying "force merge" or something (ideally along with a justification).

**Comment by ktf** [comment]
Better late than never... I think this is now taken care of by Github protected branches. Feel free to bring it up in WP3 any other comments you might have about the way it currently works.
