### ISSUE TITLE
Feature request: post the relevant information of the logfile

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/ali-bot#441]
As a user I would like to have a short message with the relevant information about the failed test in the github post, not the beginning of the logfile.

**Comment by ktf** [comment]
This is already what happens. You get the end of the log file only if that summary message cannot be created (e.g. the error is not clearly marked with `error:[0-9]+[0-9]+`. Am I misunderstanding your question?

**Comment by matthiasrichter** [comment]
ah good. My case is here https://github.com/AliceO2Group/AliceO2/pull/348 , has to be checked why extraction doesn't  work. It's a very long logfile and the relevant message is on the second last line.

**Comment by matthiasrichter** [comment]
second last line is actually the output of the grep, then this could be posted

**Comment by matthiasrichter** [comment]
I think I understand better now. The actual compilation works without error, and what is shown in the post is the end of the log of the compilation. But then there is the second steps (ore further multiple steps) checking the coding convention. This is where it failed, but the post seems to be generated from the wrong log file.
